[CLS-1466][KMS] 카테고리 추가, 삭제, 수정 로직 변경 및 토스트 추가
CloserLabs/deskroom pull request #104
Opened 2024-04-28 16:39 UTC by GyoHeon

## 버그 수정
첫 진입 페이지 (knowledge base)의 url 구조가 변경 됨에 따라 sidebar, org context 등이 org를 받지 못하는 에러가 있습니다.
전체적인 url 구조의 설계를 하는 것이 장기적으로 좋은 방향이겠으나, 일단은 org를 따라가는 query parameter를 추가하여 에러를 고쳤습니다.

## 카테고리 정보 변경 시 토스트 추가
카테고리 정보가 변경 되면 모달을 닫고 토스트로 이를 알리는 로직을 추가했습니다.

2024-04-28 22:56 UTC, ahnsv requested changes

2024-04-28 22:56 UTC, ahnsv commented on client/apps/web/src/components/TopNav.tsx
> +    router.push(`/${selectedOrg.key}?org=${selectedOrg.key}`)
중복으로 query param을 붙히는 건 좋지는 않은 방향 같습니다 path param으로만 해서 useParam으로 받아오는 건 어떨까요?

2024-04-28 23:00 UTC, ahnsv commented
Pr 코멘트를 나중에 읽어봤는데 당장에 동작하게 만드는것도 좋지만, 전반적으로 데이터 fetching 방법을 일관성 있게 만들기 위해  [orgKey] 디렉토리 아래로 위치하도록 바꾸는 게 좋을거 같습니다

2024-04-29 01:47 UTC, GyoHeon commented
url path 일관성을 위해 말씀해주신 방향으로 작업해보겠습니다.

2024-04-29 12:20 UTC, GyoHeon commented
orgKey 를 search params로 받는 로직을 전부 pathname으로 받도록 수정했습니다.
이 과정에서 usePathname을 사용하면 컴포넌트를 client로 사용해야 하기 때문에 middleware로 pathname을 받도록 하고 이 요소의 이름에 커스텀한 값임을 나타내기 위해 *x-pathname*으로 설정했습니다.

참고: https://github.com/vercel/next.js/discussions/43657#discussioncomment-5981981

2024-04-29 12:39 UTC, ahnsv requested changes

2024-04-29 12:39 UTC, ahnsv commented on client/apps/web/src/app/[orgKey]/page.tsx
> +  const orgKey = pathname.split("/")[1]
요 부분은 App router의 dynamic route 기능을 이용한건데, 
이렇게 바꾸시게 된 이유가 있을까요? useParams를 사용하기 위해서 매번 Path name을 파싱을 해야하는 건 좋은 경험인거 같지 않아 보여 우려됩니다.

2024-04-29 12:39 UTC, ahnsv commented on client/apps/web/src/app/[orgKey]/page.tsx
> +  const orgKey = pathname.split("/")[1]
client <> server 컴포넌트에서 일관된 형태로 pathname을 가져오게 된다는 장점은 있겠지만 저는 지금 보기에는 득보다는 실이 더 크지 않을까 생각이 들어서요. header에서 가져오는 방식으로 바뀌어 버리면 데이터를 가져오기 위한 파싱 과정 사이에 휴먼 에러도 많이 발생하지는 않을까요?

제가 이해하고 있기로 서버 컴포넌트에서는 데이터 fetching, 클라이언트 컴포넌트에서는 UI를 그리는 것이 app router의 가장 큰 장점이자 키 포인트라고 생각했습니다. 클라이언트 컴포넌트에서 header로 부터 -> pathname을 가져와 -> org key를 꺼내는 과정이 필요하다면, 그건 컴포넌트 설계가 잘못된 게 아닐까요?

정 필요한 경우에 usePathname은 client component에서 사용하고 server component와 client component의 pathname을 찾는 방식을 분리하는 게 어떨까 싶은데 어떻게 보시나요?

2024-04-29 13:38 UTC, GyoHeon commented
문제 상황에 너무 몰두해서 쉬운길을 놔두고 돌아갔네요!
dynamic router 기능을 되살려 page 에서 params를 받도록 수정했습니다!

client components (여기에선 sidebar)에서 휴먼 에러를 줄이는 방법은 더 고려해보면 좋을 것 같습니다.

2024-04-29 13:57 UTC, ahnsv approved these changes
코멘트 참고해주시고, 개발 환경에서 지금 확인할 수 있는 유저 정보 DM으로 전달드리겠습니다.

2024-04-29 13:57 UTC, ahnsv commented on client/apps/web/src/app/[orgKey]/categories/CategoryTable.tsx
>          <Toast.Root
P5: Toast는 뭔가 context 만들어두면 편할거 같긴하네용 나중에 context로 만들고 useToast 이런 걸로 편하게 쓰실 수 있게 하시죵

2024-04-29 13:57 UTC, ahnsv commented on client/apps/web/src/components/Sidebar.tsx
> +  const org = pathname.split("/")[1]
일관성 있게 
```suggestion
  const { orgKey } = useParams<{ orgKey: string }>()
```
로 하는 건 어떨까요?

2024-04-29 13:57 UTC, ahnsv commented on client/apps/web/src/components/Sidebar.tsx
> +  const menuPath = pathname.split("/")[2] || ""
요친구는 안타깝게도 nextjs useParams에서는 바로 안되나 보네요. 
나중에 한번 래핑해서 `/[orgKey]/[some other key]` 이런거도 바로 나올 수 있게 하는 hooks 하나 파두면 편하겠네용

2024-04-29 13:57 UTC, ahnsv commented on client/apps/web/src/app/[orgKey]/categories/CategoryTable.tsx
> +  const selectedOrg = categories[0]?.org_key
얘도 그냥 useParams 쓰는 건 어떨까요?

2024-04-29 14:09 UTC, ahnsv commented
음 preview에서 하면 category 등록이 안되는데... 로컬에서 재현되나요?

2024-04-29 14:22 UTC, GyoHeon commented
로컬에서도 서버 액션이 동작을 했다가 안했다가 하는 에러가 있네요.
수정해서 올리도록 하겠습니다.

2024-04-29 14:32 UTC, GyoHeon commented
dialog에서 orgkey를 물지 못하는 에러가 있었던 것 같습니다.(context에서 가져왔던듯 합니다.)
이번 버전에서 다시 한 번 테스트 부탁드립니다~

2024-04-30 13:12 UTC, ahnsv approved these changes

2024-04-30 13:34 UTC, merged