[CLS-1501] Fix bug that table is updated even if the value is None
CloserLabs/deskroom pull request #120
Opened 2024-05-02 02:52 UTC by heumsi

2024-05-02 11:19 UTC, ahnsv requested changes

2024-05-02 11:19 UTC, ahnsv commented on server/deskroom/categories/endpoints.py
> +        response = await supabase.table("knowledge_categories").insert(data).execute()
```suggestion
        response = await supabase.table("knowledge_categories").insert(request.dict(exclude_none=True)).execute()
```
요렇게 하면 없는 것들을 뺀 체로 나올거에요. 
https://docs.pydantic.dev/1.10/usage/exporting_models/#modeldict

2024-05-02 11:19 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +        response = await supabase.table("knowledge_base").insert(data).execute()
상동

2024-05-02 11:19 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +            .update(data)
상동

2024-05-02 11:19 UTC, ahnsv commented on server/deskroom/tags/endpoints.py
> +    category_id = request.category_id
UpdateTagsIn 이라는 DTO가 여기서만 사용한다면 endpoint layer의 복잡한 로직을 DTO class 안으로 옮길 수 있지 않을까요? 

```suggestion
class UpdateTagsIn(Schema):
    ...
    def get_insert_payload(self):
        return {"category_id": self.category_id, "question_id": self.knowledge_base_id}
```

2024-05-03 01:49 UTC, ahnsv approved these changes
코멘트 확인 해주세요! 그나저나 dto로 로직 옮기는 거 생각보다 간결하진 않네요 ㅠ

2024-05-04 02:12 UTC, heumsi commented on server/deskroom/tags/endpoints.py
> +    # current_user: DeskroomUser = Depends(get_current_user),
```suggestion
    current_user: DeskroomUser = Depends(get_current_user),
```

2024-05-04 06:19 UTC, ahnsv commented
일단 요거 머지할게요!

2024-05-04 06:19 UTC, merged