Refactor/endpoint migration
CloserLabs/deskroom pull request #20
Opened 2024-04-08 07:08 UTC by shawnhyeonsoo

2024-04-09 06:28 UTC, shawnhyeonsoo commented
* Retrieval
* Retrieval w/ category
* Azure Openai Migration

2024-04-09 09:31 UTC, ahnsv requested changes

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/common/openai.py
> +        prompt = byte_data.readall().decode("utf-8")
로컬에서 파일을 한번 찾고 없으면 azure를 찾는 거 보다 명시적으로 환경 별로 구분하는 건 어떨까요?

```suggestion
    if setting.local():
        with open(PROMPT_PATH / txt_file_from_prompts_dir) as file:
            prompt_file = file.readlines()
        prompt = "\n".join(prompt_file)
    else:
        container_client = create_azure_container_client("prompts")
        byte_data = container_client.download_blob(str(txt_file_from_prompts_dir))
        prompt = byte_data.readall().decode("utf-8")
```

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/common/supabase.py
> +async def create_supabase_client() -> Client:
이건 왜 async일까요? sync 아닐까요?

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/config.py
> +    OPENAI_API_KEY: str = Field("deskroom_openai", alias="OPENAI_API_KEY")
Field 클래스의 첫번째 인자는 default 값인걸로 아는데 default 값을 이렇게 해두면 에러가 나야할 상황에서 나지 않아서 (환경 변수 주입이 안되었는데 됐다고 판단할 수 도 있으니), None혹은 `...` 로 두는 게 어떨까 싶은데 어떻게 생각하시나요

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +    org_info = supabase_response.data[0]
index error가 나기 쉬운 코드로 보입니다. 
```suggestion
    org_info = next(supabase_response.data, None)
    if not org_info:
        raise SomeError("some error description")
```
요렇게 하는 게 더 안전하지 않을까요? 클라이언트 입장에서는 500만 뜰거라서 무슨 에러가 나는 지 알수가 없어서요.

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +        except BaseException:
```suggestion
        except (ValueError, KeyError):
```
BaseException은 모든 python 에러들의 상위 클래스입니다. 이렇게 되면 이 라인에서 value가 잘못 된건지, 단순한 runtime error인지 크리티컬한 에러인지 모르게 될 수 있습니다. 

Golden rule은
1. try-except를 최대한 적은 라인으로 유지하세요.
2. 에러 핸들링하는 케이스는 최대한 좁게 유지하세요. 
이 케이스에는 그냥 디버깅하기 편하라고 해둔거 같아서 에러 스코프를 최대한 좁혀주세요.

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +            pass
의미가 없습니다.
```suggestion

```

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/knowledge_base/utils.py
> +        except BaseException:
상동

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/retrieve/endpoints.py
> +            pass
상동

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/retrieve/endpoints.py
> +    )
```suggestion

    if supabase_response.error:
        raise HttpException(status=400, detail="데이터가 없습니다.")
        
    retrieved_msgs = await retrieve_and_process(
        qn=knowledge_query_in.question, knowledge_base=supabase_response.data
    )
```
retrieve_and_process와 같은 비싼 작업 이전에 위 쿼리의 결과물을 먼저 검사해서 쓸모없이 gpt token을 쓰는 일을 막아주는 게 좋겠습니다.

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/retrieve/__init__.py
domain 별로 나누기로 했으니, 나중에는 retrieve라는 동사형은 버리고, categories와 knowledge_base로 나눠가져가면 일관성있겟네요.

2024-04-09 09:31 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +    for _ in range(len(update_df)):
```suggestion
    for row_num in range(len(update_df)):
```
_는 파이썬에서 사용하지 않는 변수를 구조화해야할 때 사용합니다. 변수 하나하나에 읽는 사람을 고려해주세요.

2024-04-10 02:05 UTC, shawnhyeonsoo commented on server/deskroom/common/supabase.py
> +async def create_supabase_client() -> Client:
아 그러네요 async client랑 헷갈렸네요.. 감사합니다

2024-04-10 02:08 UTC, shawnhyeonsoo commented on server/deskroom/config.py
> +    OPENAI_API_KEY: str = Field("deskroom_openai", alias="OPENAI_API_KEY")
동의합니다

2024-04-10 02:17 UTC, shawnhyeonsoo commented on server/deskroom/knowledge_base/endpoints.py
> +    org_info = supabase_response.data[0]
음... 이걸 사용하는게 org_id랑 name_eng밖에 없는데 해당하는 key값이 테이블안에 있다면 id랑 name도 있을테니 supabase table query할때 error 체크하게 바꿔보겠습니다

2024-04-10 07:47 UTC, ahnsv requested changes

2024-04-10 07:47 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +            pass
아무 핸들링을 안해줘도 되나요?

2024-04-10 07:47 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +        data = await supabase.table("knowledge_base").insert(updated_files).execute()
Insert문은 list로 들어가서 for 문에서 매번 넣는거보다, 한 번에 넣는게 더 좋을거에요 (단, 1000개 데이터 이상 벌크는 오히려 떨어질듯)

```suggestion
    response = await supabase.table("knowledge_base").insert([updated_files for row_num in updated_df]).execute()
```

2024-04-10 07:47 UTC, ahnsv commented on server/deskroom/knowledge_base/utils.py
> +            pass
여기도 의미없는 try-except 인거 같습니다

2024-04-10 07:47 UTC, ahnsv commented on server/deskroom/retrieve/endpoints.py
> +            pass
상동

2024-04-10 07:47 UTC, ahnsv commented on server/deskroom/retrieve/endpoints.py
> +    supabase_response = (
Error handling 필요

2024-04-10 07:47 UTC, ahnsv commented on server/deskroom/knowledge_base/endpoints.py
> +        raise ValueError("No ID / Name for given Org Key")
Value error를 내버리면 클라 입장에서는 500이라 무슨일이 일어났는 지 모를거에요.

1. HttpException을 명시적으로 내준다
2. Fastapi Global exception guard를 만들어서 처리한다

중에 선택하는 대안이 있겠네요.

2024-04-11 00:39 UTC, ahnsv commented on server/deskroom/retrieve/endpoints.py
> +            pass
다시보니 pass -> continue로 바꾸는 게 더 명시적일거 같네요.

2024-04-11 04:00 UTC, shawnhyeonsoo commented on server/deskroom/common/openai.py
> +        byte_data = container_client.download_blob(str(txt_file_from_prompts_dir))
이 부분은 다음 PR에 포함시키겠습니다

2024-04-11 04:44 UTC, ahnsv approved these changes
일단 머지 해보고, https://api-dev.deskroom.so/docs 에서 잘 동작하는 지 확인 한번 해주세요. LGTM

2024-04-11 04:45 UTC, merged