[CLS-1375] extension api 수정
CloserLabs/deskroom pull request #69
Opened 2024-04-22 15:41 UTC by shawnhyeonsoo

입력 category null시 모든 카테고리 데이터 호출

2024-04-22 22:26 UTC, ahnsv requested changes

2024-04-22 22:26 UTC, ahnsv commented on server/deskroom/retrieve/endpoints.py
> +    if knowledge_query_in.category == "" or knowledge_query_in.category is None:
```suggestion
    if !knowledge_query_in.category:
```
요렇게 줄일수 있겠네용

2024-04-23 02:18 UTC, shawnhyeonsoo commented on server/deskroom/retrieve/endpoints.py
> +    if not knowledge_query_in.category:
@ahnsv 이렇게 수정했는데 다시 한번 확인 부탁드립니다!

2024-04-23 02:32 UTC, ahnsv approved these changes
Lgtm

2024-04-23 02:38 UTC, merged