feat(server): Add authN into all API endpoints
CloserLabs/deskroom pull request #82
Opened 2024-04-25 06:56 UTC by heumsi

## Summary

Add authN into all API endpoints

## Changes

- Add fastapi dependency function `get_current_user(...)`
- Add `current_user: User = Depends(get_current_user)` param into all API endpoint functions'
- Add `GET /v1/auth/me` endpoint
  - This is used to test whether `current_user: User = Depends(get_current_user)` work well
- Update `README.md` for local test

## Test Result

```
(.venv) ~/Desktop/heumsi/projects/closer-labs/deskroom/server (feature/CLS-1219 ✗) poetry run task test
============================================== test session starts ==============================================
platform darwin -- Python 3.10.6, pytest-8.1.1, pluggy-1.4.0
rootdir: /Users/user/Desktop/heumsi/projects/closer-labs/deskroom/server
configfile: pyproject.toml
plugins: anyio-3.7.1
collected 6 items                                                                                               

tests/test_app.py .                                                                                       [ 16%]
tests/test_auth.py ....                                                                                   [ 83%]
tests/test_openai.py .                                                                                    [100%]

=============================================== warnings summary ================================================
tests/test_app.py::test_get_all_users
  /Users/user/Desktop/heumsi/projects/closer-labs/deskroom/server/deskroom/app.py:39: DeprecationWarning: 
          on_event is deprecated, use lifespan event handlers instead.
  
          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
          
    @app.on_event("startup")

tests/test_app.py::test_get_all_users
tests/test_app.py::test_get_all_users
  /Users/user/Desktop/heumsi/projects/closer-labs/deskroom/server/.venv/lib/python3.10/site-packages/fastapi/applications.py:4547: DeprecationWarning: 
          on_event is deprecated, use lifespan event handlers instead.
  
          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
          
    return self.router.on_event(event_type)

tests/test_app.py::test_get_all_users
  /Users/user/Desktop/heumsi/projects/closer-labs/deskroom/server/deskroom/app.py:43: DeprecationWarning: 
          on_event is deprecated, use lifespan event handlers instead.
  
          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
          
    @app.on_event("shutdown")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================= 6 passed, 4 warnings in 1.08s =========================================
^CException ignored in: <module 'threading' from '/Users/user/.pyenv/versions/3.10.6/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

I'm having trouble getting my tests to finish. Probably there is some unresolved lock on the thread during the server shutdown process. This issue is not caused by this change, so I'm just checking the test results for now.

2024-04-25 10:25 UTC, ahnsv requested changes
테스트가 터지는 이유는 DSKRM_SUPABASE_SERVICE_ROLE_KEY 환경 변수가 pre-merge step의 환경변수에 지정되지 않아서로 보입니다.

2024-04-25 10:25 UTC, ahnsv commented on server/README.md
> +service_role key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
이거 실제 키 아니죠...?

2024-04-25 10:25 UTC, ahnsv commented on server/deskroom/config.py
> +    SUPABASE_SERVICE_ROLE_KEY: str = Field("", alias="DSKRM_SUPABASE_SERVICE_ROLE_KEY")
```suggestion
    SUPABASE_URL: str = Field("")
    SUPABASE_ANON_KEY: str = Field("")
    SUPABASE_SERVICE_ROLE_KEY: str = Field("")
```

pydantic 2.0 이상, pydantic_settings 모듈을 사용하면 model_config 의 env_prefix가 자동으로 붙어서 alias를 지정할 필요가 없어졌습니다. 다른 field들 중 alias가 있는 것들은 외부 디펜던시 (env 이름이 이미 지정이 되어있는 경우) 가 있는 것들입니다. 
(사실 Azure 쪽은 아닌데 어쩌다보니 그냥 넘어간듯)

2024-04-25 10:25 UTC, ahnsv commented on server/supabase/config.toml
> +# A string used to distinguish different Supabase projects on the same host. Defaults to the
config.toml 파일이 여기에서 하는 역할은 무엇일까요?

2024-04-25 10:56 UTC, heumsi commented on server/README.md
> +service_role key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
로컬에서 `supabase start` 로 stdout으로 뜨는 값들 입니다. 실행할 때 마다 달라져서 그냥 올렸습니다.

2024-04-25 10:57 UTC, heumsi commented on server/deskroom/config.py
> +    SUPABASE_SERVICE_ROLE_KEY: str = Field("", alias="DSKRM_SUPABASE_SERVICE_ROLE_KEY")
처음에 `alias` 값으로 `SUPABASE_URL` 만 하니, 인식이 안되었습니다. 위처럼 `DSKRM_SUPABASE_URL` 를 하니 인식이 되더군요. 제가 뭔가 놓치고 있는게 있을까요?

2024-04-25 11:02 UTC, heumsi commented on server/supabase/config.toml
> +# A string used to distinguish different Supabase projects on the same host. Defaults to the
`supabase init` 실행 시 만들어지는 설정 값으로, `supabase start` 시 이 파일을 참고합니다.
이 파일로 있음으로 이후에 `supabase init` 을 하지 않아도 됩니다.

2024-04-25 11:31 UTC, ahnsv commented on server/deskroom/config.py
> +    SUPABASE_SERVICE_ROLE_KEY: str = Field("", alias="DSKRM_SUPABASE_SERVICE_ROLE_KEY")
넵 놓치고 있는 게 있는 거 같아요 
https://docs.pydantic.dev/latest/concepts/pydantic_settings/
여기 한번 읽어보심 이해가 갈듯. 당연히 alias 입력을 안하면 SUPABASE_URL 로 인식이 안됩니다.

2024-04-25 11:32 UTC, ahnsv commented on server/README.md
> +service_role key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
```suggestion
        anon key: eyJhbGciOiJIUzI1...redacted
service_role key: eyJhbGciOiJIU...redacted
```

요렇게 하시죠
FYI: redact - https://dictionary.cambridge.org/dictionary/english/redact
MS 쪽에서 이렇게 처리를 많이 하더라고요.

2024-04-25 11:32 UTC, ahnsv commented on server/supabase/config.toml
> +# A string used to distinguish different Supabase projects on the same host. Defaults to the
으음... supabase start를 왜 해야하는 걸까요...?

2024-04-25 11:35 UTC, ahnsv commented
@heumsi 음 service role 키라는 걸 매번 발급을 해줘야 이 모든 로직이 가능해지는 걸까요? 그렇다면 이 코드를 실행하는 유저의 로컬에서나, 서버 환경 등 모든 환경의 runtime에서 실행해줘야할 거 같은데, 이는 원하는 바가 아닙니다. service role key 없이 하는 방법은 정말 없었을까요?

2024-04-25 12:15 UTC, heumsi commented on server/supabase/config.toml
> +# A string used to distinguish different Supabase projects on the same host. Defaults to the
> supabase start를 왜 해야하는 걸까요...?

테스트 코드를 실행할 때 사용할 supabase가 필요한데, 현재는 사용할 supabase가 없습니다. (운영용 supabase만 존재)
그래서 테스트 코드 실행 전에 로컬에서 supabase를 사용하려고 하는거구요.

2024-04-25 12:22 UTC, heumsi commented
> service role 키라는 걸 매번 발급을 해줘야 이 모든 로직이 가능해지는 걸까요?

테스트 코드에서 로컬 supabase에 값을 추가 후, 추가한 값들을 clean 하기 위해 table의 값을 삭제하는데요. 이 때 일반 `anon_key` 로는 권한이 없고, `service_role_key` 로 가능합니다. (이게 Postgresql에 어드민 권한 가지고 있는 계정이라고 하는군요)

보통 각 테스트 함수의 독립성을 위해 테스트 코드 실행 앞 혹은 뒤로 DB 클린업을 해주는데요. 
이 때 `service_role_key` 없이 클린업을 해주는 방법은 없을거 같습니다. DELETE 하는거 자체가 저 계정을 필요로 하는 거라서요.

이 값을 매번 발급하는게 문제라면, 로컬 supabase를 사용하지 않고, **cloud supabase에 test용 프로젝트를 만든 뒤, 한번 발급된 `service_role_key` 를 사용하는건 어떨까요?** 이러면 테스트 환경 구성도 더 쉬울거 같구요. (다만 네트워크 의존성이 있고, 테스트 때마다 cloud supabase를 사용하므로 cloud usage 및 비용이 증가할 수 있음)

@ahnsv

2024-04-25 12:32 UTC, ahnsv commented
> > service role 키라는 걸 매번 발급을 해줘야 이 모든 로직이 가능해지는 걸까요?
> 
> 테스트 코드에서 로컬 supabase에 값을 추가 후, 추가한 값들을 clean 하기 위해 table의 값을 삭제하는데요. 이 때 일반 `anon_key` 로는 권한이 없고, `service_role_key` 로 가능합니다. (이게 Postgresql에 어드민 권한 가지고 있는 계정이라고 하는군요)
> 
> 보통 각 테스트 함수의 독립성을 위해 테스트 코드 실행 앞 혹은 뒤로 DB 클린업을 해주는데요. 이 때 `service_role_key` 없이 클린업을 해주는 방법은 없을거 같습니다. DELETE 하는거 자체가 저 계정을 필요로 하는 거라서요.
> 
> 이 값을 매번 발급하는게 문제라면, 로컬 supabase를 사용하지 않고, **cloud supabase에 test용 프로젝트를 만든 뒤, 한번 발급된 `service_role_key` 를 사용하는건 어떨까요?** 이러면 테스트 환경 구성도 더 쉬울거 같구요. (다만 네트워크 의존성이 있고, 테스트 때마다 cloud supabase를 사용하므로 cloud usage 및 비용이 증가할 수 있음)
> 
> 한편 이 모든게 너무 과하다고 생각한다면, 테스트 환경 구축 때문에 발생하는 일이니, 추가된 테스트 코드를 삭제하는 방법도 있습니다.
> 
> @ahnsv

아하 그런 맥락에서 나온 거군요. 저는 아직은 overkill인거 같습니다. 나중에 orm으로 말면 핫시죠 요건!

2024-04-25 12:41 UTC, heumsi commented
그러면 테스트 코드 모두 주석처리 해두겠습니다!

2024-04-25 12:55 UTC, heumsi commented
@ahnsv 리뷰 요청 드립니다

2024-04-26 04:38 UTC, ahnsv approved these changes

2024-04-26 07:35 UTC, merged